channels:
- conda-forge
dependencies:
- python=3.11.13
- pip<=25.1
- pip:
  - mlflow==2.11.3
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - packaging==23.2
  - psutil==7.0.0
  - pyyaml==6.0.1
  - scikit-learn==1.4.1.post1
  - scipy==1.16.0
name: mlflow-env
